name = "UKF"
uuid = "881e0322-98f6-4d75-bd72-33b54f43ab40"
authors = ["Juraj Lieskovský <lieskovsky.juraj@gmail.com>"]
version = "0.1.0"

[deps]
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Debugger = "0.7.10"
LinearAlgebra = "1.11.0"
